[config]
schemaVersion = "0.0.1"

[package]
namespace = "morphine"
name = "PvPDetails"
versionNumber = "0.2.0"
description = "PvP Leaderboard, killfeed, and post fight breakdowns."
websiteUrl = "https://github.com/phlebotomist/Killfeed"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"
deca-Bloodstone = "0.2.2"

[build]
icon = "./logo.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]

[publish.categories]
v-rising = ["gloomrot-update", "mods", "server"]
